apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Values.appName }}-app
          image: {{ .Values.image.name}}:{{ .Values.image.tag}}
          args:
            - {{ .Values.outText }}
